version: "3"

services:
  mysql:                               # 服务名称
    image: mysql:5.7                   # 使用的镜像
    restart: always                    # 自动重启
    ports:                             # 端口映射
      - 3306:3306
    volumes:                           # 文件挂载
      - ./mysql/conf:/etc/mysql        # 挂载配置文件
      - ./mysql/log:/var/log/mysql     # 挂载日志目录
      - ./mysql/data:/var/lib/mysql    # 挂载数据目录
    command: [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
    ]
    environment:                       # 环境变量
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis:7.0.5
    restart: always
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf    # 可使用文档中的redis.conf自定义密码
      - ./redis/logs:/logs
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
    environment:
      - TZ=Asia/Shanghai
  rabbitmq:
    image: rabbitmq:3.8.3-management
    restart: always
    privileged: true
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq/
    environment:
      - TZ=Asia/Shanghai
  nginx:
    image: nginx:1.22.1
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 设置时间跟随宿主机
      - ./nginx/log/:/var/log/nginx
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./vsftp/data:/home/ftp
  vsftp: # 参考链接：https://blog.csdn.net/m0_58684193/article/details/124817438
    image: shourai/vsftpd-alpine:latest
    restart: always
    ports: # 踩坑：yml支持以60为底的浮点数，如果没有大于60的数，则20:20会被记为20*60+20，解决办法是用双引号括起来（参考链接：https://www.cnblogs.com/zerchin/p/14797983.html）
      - "20:20"
      - "21:21"
      - 21100-21110:21100-21110
    environment:
      - FTP_USER=admin        # 自定义用户名
      - FTP_PASS=123456       # 自定义用户密码
      - PASV_ENABLE=YES
      - PASV_ADDRESS=192.168.164.130    # 宿主机的IP
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - ANON_ENABLE=NO
      - NO_ANON_PASSWD=NO
      - ANON_ROOT=/var/ftp
    volumes:  # 踩坑：文件夹"./vsftp/data"不要在宿主机手动创建，否则容器存在权限问题，上传文件失败，docker-compose启动时会自动创建
      - ./vsftp/data:/home/admin    # 与FTP_USER保持一致,即$FTP_USER的值是什么此处的目录就是什么
